name: Sync content from Google Drive

on:
  workflow_dispatch:  # manual trigger from GitHub UI

jobs:
  sync-drive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download files from Google Drive
        run: |
          mkdir -p sync
          cd sync

          # Replace with actual file IDs and filenames
          curl -L -o home.txt        "https://drive.google.com/uc?export=download&id=1JpL-DtZwTtx7S4rdXSXlGJe090K6Uvvi"
          curl -L -o volunteer.txt   "https://drive.google.com/uc?export=download&id=11Sm4v0g_2N7knjczwlXtQsoJ959KHPbP"
          curl -L -o events.csv      "https://drive.google.com/uc?export=download&id=1E_ccXNQyJk8vkOcuReRcxNnBEX7SSofR"
          curl -L -o newsletters.csv "https://drive.google.com/uc?export=download&id=1awgfJgW7H3J-9cQrD7p16C9rrKmaLLxS"
          curl -L -o logo.png        "https://drive.google.com/uc?export=download&id=186lYlRh0UhFGaIcb2GcKm575yz6oswFn"

          # Move downloaded files to root
          mv * ../
          cd ..

      - name: Commit and push updates
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add home.txt volunteer.txt events.csv newsletters.csv logo.png
          git commit -m "Update content from Google Drive" || echo "No changes to commit"
          git push
